# Numpy Basics

In [1]:
import numpy as np

---
### Creating Arrays

**from Python list**

In [2]:
a_python_list = [1, 2, 3, 4, 5] * 3
a_python_list

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [4]:
arr_1 = np.array(a_python_list)
print(arr_1.dtype)
print(arr_1.shape)
arr_1

int32
(15,)


array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5])

In [5]:
arr_2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2.dtype)
print(arr_2.shape)
arr_2

int32
(3, 3)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**arange**

In [55]:
np.arange(0, 10, 1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
np.arange(-10, 10, 3)

array([-10,  -7,  -4,  -1,   2,   5,   8])

**fill**

In [60]:
np.full((2, 3), 999)

array([[999, 999, 999],
       [999, 999, 999]])

**zeros** and **ones**

In [61]:
np.zeros((10, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [62]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [67]:
(np.ones((2, 2)) * 999).astype(np.int16)

array([[999, 999],
       [999, 999]], dtype=int16)

**linspace**

In [68]:
np.linspace(-1, 1, 20)

array([-1.        , -0.89473684, -0.78947368, -0.68421053, -0.57894737,
       -0.47368421, -0.36842105, -0.26315789, -0.15789474, -0.05263158,
        0.05263158,  0.15789474,  0.26315789,  0.36842105,  0.47368421,
        0.57894737,  0.68421053,  0.78947368,  0.89473684,  1.        ])

**eye**

In [70]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

**random**

between 0 and 1

In [73]:
np.random.rand(2, 4)

array([[0.2460831 , 0.02867381, 0.3453213 , 0.85192987],
       [0.29555036, 0.1164007 , 0.76427592, 0.31386218]])

from standard normal distribution
-> mean is 0 and standard variation is 1

In [74]:
np.random.randn(4)

array([-0.17793993,  0.44376175,  0.48293298,  0.40353278])

In [77]:
# loc = mean value
# scale = standard variation
np.random.normal(loc=100, scale=2, size=(2,2))

array([[ 99.73530812,  98.65454404],
       [ 98.37845171, 101.62601436]])

random integers

In [78]:
np.random.randint(0, 2, (3, 1))

array([[1],
       [0],
       [1]])

---
### Methods

Many methods are also as Numpy Functions available

In [6]:
arr_2.dtype

dtype('int32')

In [7]:
arr_2.shape

(3, 3)

In [8]:
arr_2.astype(np.float64).dtype

dtype('float64')

In [10]:
arr_2.all()

True

In [11]:
arr_2.any()

True

In [ ]:
arr_2.argmax()    # returns the index of the max value

8

In [14]:
arr_2.max()

9

In [17]:
arr_2.flatten()[arr_2.argmax()]

9

In [18]:
arr_2.mean()

5.0

In [19]:
arr_2.sum()

45

In [147]:
arr_2.sum(axis=0)

array([12, 15, 18])

In [148]:
arr_2.sum(axis=1)

array([ 6, 15, 24])

In [145]:
arr_2.std()

2.581988897471611

In [146]:
arr_2.var()

6.666666666666667

In [ ]:
arr_2.transpose((1, 0))

In [ ]:
arr_2.ravel()   # flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

... there are much more ...

---
### Numpy Functions

Many numpy functions are also as methods available

In [143]:
np.sqrt(arr_2)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [144]:
np.log(arr_2)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [20]:
np.unique(arr_2)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.count_nonzero(arr_2)

9

In [25]:
np.sin(1)

0.8414709848078965

In [26]:
np.e

2.718281828459045

In [27]:
np.pi

3.141592653589793

In [28]:
np.inf

inf

In [29]:
np.absolute(-33)

33

In [49]:
np.squeeze(np.array([ [0, 1, 2] ]))

array([0, 1, 2])

In [51]:
np.clip(arr_2, a_max=3, a_min=2)

array([[2, 2, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [52]:
np.reshape(arr_2, (-1))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
np.reshape(arr_2, (1, -1))

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
#        condition   true      false
np.where(arr_2 > 3, arr_2**2, arr_2//2)

array([[ 0,  1,  1],
       [16, 25, 36],
       [49, 64, 81]], dtype=int32)

In [94]:
np.copy(arr_2)    # important, because slices and other copies will effect (side effect) the original array, if not using this method

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

...and there are much more...

In [98]:
np.nan

nan

In [ ]:
nan_arr = np.array([np.nan, 10, 40, -20, np.nan, 40])
np.where(np.isnan(nan_arr), 999, nan_arr)

array([999.,  10.,  40., -20., 999.,  40.])

In [137]:
inf_arr = np.array([np.inf, 10, 40, -20, np.inf, 40])
np.where(np.isinf(inf_arr), 999, inf_arr)

array([999.,  10.,  40., -20., 999.,  40.])

---
### Slicing and Indexing

In [83]:
arr_2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [82]:
arr_2[0]

array([1, 2, 3])

In [ ]:
arr_2[0][1]    # or: arr_2[0, 1]

2

In [ ]:
arr_2[0][1:3]    # or: arr_2[0, 1:3] 

array([2, 3])

In [ ]:
arr_2[0:2][1]    # or: arr_2[0:2, 1]

array([4, 5, 6])

In [96]:
arr_2[0:2, 1:3]

array([[2, 3],
       [5, 6]])

Using Bool Masks -> can be very useful

In [80]:
arr_2[arr_2 > 3]

array([4, 5, 6, 7, 8, 9])