# PyTorch Basics

In [1]:
import numpy as np
import torch

In [2]:
torch.__version__

'1.9.1+cpu'

---
### Create Tensors from Numpy

Tensors are n-dimensional arrays:

- 1 value = scalar -> 99
- 1 dim values = vector = 1d tensor -> [99, 99, 99]
- 2 dim values = matrix = 2d tensor -> [[99,99,99], [99,99,99], [99,99,99]]
- \>= 3 dim values = n-dim tensor

**from_numpy** and **as_tensor** -> both will link to the original numpy array with sideeffects

In [3]:
arr = np.arange(1, 6)
print(arr.dtype)
print(type(arr))
arr

int32
<class 'numpy.ndarray'>


array([1, 2, 3, 4, 5])

In [4]:
tensor = torch.as_tensor(arr)    # or: from_numpy    -> from_numpy
print(tensor.dtype)
print(type(tensor))
tensor

torch.int32
<class 'torch.Tensor'>


tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [ ]:
# sideeffect:

arr[0] = -99
print(arr)

print(tensor)

[-99   2   3   4   5]
tensor([-99,   2,   3,   4,   5], dtype=torch.int32)


**tensor** -> without sideeffect, so this version is recommended

In [6]:
arr = np.arange(1.0, 7.0, 0.5).reshape((3, 4))
print(arr.dtype)
print(type(arr))
print(arr, "\n\n")

tensor = torch.tensor(arr)
print(tensor.dtype)
print(type(tensor))
print(tensor)

float64
<class 'numpy.ndarray'>
[[1.  1.5 2.  2.5]
 [3.  3.5 4.  4.5]
 [5.  5.5 6.  6.5]] 


torch.float64
<class 'torch.Tensor'>
tensor([[1.0000, 1.5000, 2.0000, 2.5000],
        [3.0000, 3.5000, 4.0000, 4.5000],
        [5.0000, 5.5000, 6.0000, 6.5000]], dtype=torch.float64)


In [ ]:
# without sideeffect:

arr[0] = -99
print(arr)

print(tensor)

[[-99.  -99.  -99.  -99. ]
 [  3.    3.5   4.    4.5]
 [  5.    5.5   6.    6.5]]
tensor([[1.0000, 1.5000, 2.0000, 2.5000],
        [3.0000, 3.5000, 4.0000, 4.5000],
        [5.0000, 5.5000, 6.0000, 6.5000]], dtype=torch.float64)


**tensor** vs. **Tensor**

-> torch.Tensor is same as torch.tensor, but torch.Tensor converts the array in float32

In [8]:
arr = np.linspace(-1, 1, 6).reshape((3, -1))
print("Original Numpy Array")
print(arr.dtype)
print(type(arr))
print(arr, "\n\n")

tensor_1 = torch.tensor(arr)
print("Torch Tensor created with .tensor")
print(tensor_1.dtype)
print(type(tensor_1))
print(tensor_1, "\n\n")

tensor_2 = torch.Tensor(arr)
print("Torch Tensor created with .Tensor")
print(tensor_2.dtype)
print(type(tensor_2))
print(tensor_2, "\n\n")

Original Numpy Array
float64
<class 'numpy.ndarray'>
[[-1.  -0.6]
 [-0.2  0.2]
 [ 0.6  1. ]] 


Torch Tensor created with .tensor
torch.float64
<class 'torch.Tensor'>
tensor([[-1.0000, -0.6000],
        [-0.2000,  0.2000],
        [ 0.6000,  1.0000]], dtype=torch.float64) 


Torch Tensor created with .Tensor
torch.float32
<class 'torch.Tensor'>
tensor([[-1.0000, -0.6000],
        [-0.2000,  0.2000],
        [ 0.6000,  1.0000]]) 




---
### Other Ways to create Tensors

In [ ]:
torch.empty(3, 4)    # very close to zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [10]:
torch.zeros(4, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [11]:
torch.zeros(4, 3, dtype=torch.int32)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

In [12]:
torch.ones(4, 3, dtype=torch.int32)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)

In [13]:
torch.ones(4, 3, dtype=torch.int32)*99

tensor([[99, 99, 99],
        [99, 99, 99],
        [99, 99, 99],
        [99, 99, 99]], dtype=torch.int32)

In [16]:
torch.arange(64, 112)

tensor([ 64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
         78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
         92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104, 105,
        106, 107, 108, 109, 110, 111])

In [17]:
torch.arange(64, 112).reshape((3, -1))

tensor([[ 64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
          78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,
          94,  95],
        [ 96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109,
         110, 111]])

In [52]:
torch.linspace(0, 100, 50)

tensor([  0.0000,   2.0408,   4.0816,   6.1224,   8.1633,  10.2041,  12.2449,
         14.2857,  16.3265,  18.3673,  20.4082,  22.4490,  24.4898,  26.5306,
         28.5714,  30.6122,  32.6531,  34.6939,  36.7347,  38.7755,  40.8163,
         42.8571,  44.8980,  46.9388,  48.9796,  51.0204,  53.0612,  55.1020,
         57.1429,  59.1837,  61.2245,  63.2653,  65.3061,  67.3469,  69.3878,
         71.4286,  73.4694,  75.5102,  77.5510,  79.5918,  81.6327,  83.6735,
         85.7143,  87.7551,  89.7959,  91.8367,  93.8775,  95.9184,  97.9592,
        100.0000])

In [53]:
torch.randn(3)

tensor([-0.1079, -0.7752, -0.9561])

In [54]:
torch.randn(3, 5)

tensor([[-6.9736e-03,  1.0503e+00,  5.8067e-01,  1.2229e+00,  6.2621e-01],
        [ 1.1246e-03,  3.1520e-01, -8.5308e-01,  8.6547e-01, -1.2989e+00],
        [ 3.6092e-01, -2.0384e-01,  1.0214e+00,  8.1873e-01,  2.0926e+00]])

In [ ]:
torch.rand(4, 3)

tensor([[0.8388, 0.7036, 0.5725],
        [0.6276, 0.3119, 0.8458],
        [0.0384, 0.7500, 0.1298],
        [0.4921, 0.2372, 0.9603]])

In [60]:
torch.randint(low=0, high=10, size=(5,5))    # the high number is exluded

tensor([[9, 3, 0, 8, 9],
        [6, 3, 3, 6, 3],
        [7, 8, 4, 8, 0],
        [3, 0, 0, 8, 8],
        [0, 7, 1, 1, 4]])

In [55]:
torch.tensor([1, 2, 3, 4])

tensor([1, 2, 3, 4])

In [61]:
tensor.shape

torch.Size([12])

In [63]:
torch.rand(tensor.shape)

tensor([0.1300, 0.7773, 0.0903, 0.5309, 0.2821, 0.2581, 0.1990, 0.8074, 0.5942,
        0.9583, 0.1702, 0.1372])

---
### Tensor Methods/functions

many methods have an in-place version with a sideeffect, written with the same name + _

Most of the methods are also available as funcrions using torch.method_name

In [18]:
tensor = torch.arange(0, 12)
tensor

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [30]:
tensor.shape

torch.Size([12])

In [19]:
tensor.reshape((3, -1))

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [31]:
tensor.reshape((3, -1)).shape

torch.Size([3, 4])

In [40]:
tensor.reshape((1, 3, -1)).permute((2, 0, 1)).squeeze()

tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]])

In [20]:
tensor.dtype

torch.int64

In [24]:
tensor.abs()

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [25]:
tensor.add(2)

tensor([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [26]:
tensor.multiply(5)

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

In [28]:
tensor.log()

tensor([  -inf, 0.0000, 0.6931, 1.0986, 1.3863, 1.6094, 1.7918, 1.9459, 2.0794,
        2.1972, 2.3026, 2.3979])

In [44]:
tensor.reshape((1, -1)).squeeze()

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [45]:
tensor.reshape((2, -1)).flatten()

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [46]:
tensor.reshape((2, -1)).ravel()

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [47]:
tensor.sum()

tensor(66)

In [50]:
tensor.apply_(lambda x: x**2)

tensor([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121])

In [57]:
tensor.type(torch.float16)

tensor([  0.,   1.,   4.,   9.,  16.,  25.,  36.,  49.,  64.,  81., 100., 121.],
       dtype=torch.float16)

...there are also bitwise operation and much more functionalities